"""
screener/tickers.py — Full IDX Coverage ~900+ ticker
"""

import logging
from typing import List

logger = logging.getLogger(__name__)

ALL_IDX_TICKERS: List[str] = [
    # --- PERBANKAN ---
    "BBCA.JK","BBRI.JK","BMRI.JK","BBNI.JK","BRIS.JK","BNGA.JK","BJBR.JK",
    "BDMN.JK","NISP.JK","PNBN.JK","MEGA.JK","BJTM.JK","BTPS.JK","NOBU.JK",
    "AGRO.JK","BBYB.JK","BBKP.JK","BABP.JK","AGRS.JK","BMAS.JK","BCIC.JK",
    "BGTG.JK","BINA.JK","BKSW.JK","BMBL.JK","BNBA.JK","BNII.JK","BPII.JK",
    "BSIM.JK","BTPN.JK","DNAR.JK","INPC.JK","MAYA.JK","MCOR.JK","NAGA.JK",
    "PNBS.JK","SDRA.JK","TRIM.JK","ASDM.JK","ASJT.JK","BANK.JK","BHAT.JK",
    "BBMD.JK","BBNP.JK","BEKS.JK","BGTG.JK","BPAG.JK","BSWD.JK","BYBB.JK",

    # --- TELEKOMUNIKASI & TEKNOLOGI ---
    "TLKM.JK","EXCL.JK","ISAT.JK","FREN.JK","MNCN.JK","SCMA.JK","EMTK.JK",
    "TOWR.JK","TBIG.JK","LINK.JK","MTEL.JK","DCII.JK","WIFI.JK","INET.JK",
    "MLPT.JK","DMMX.JK","DNET.JK","MTDL.JK","LUCK.JK","SWAT.JK","HAIS.JK",
    "TFAS.JK","EDGE.JK","NFCX.JK","STRK.JK","TECH.JK","ATIC.JK","CENT.JK",
    "IPTV.JK","JGLE.JK","KIOS.JK","MCAS.JK","MPIX.JK","SKYB.JK","TELE.JK",
    "DOOH.JK","DIVA.JK","ANDI.JK","AXIO.JK","BINO.JK","BSML.JK","CBPE.JK",
    "DMMX.JK","FORE.JK","GRIA.JK","HELO.JK","IMAS.JK","INKA.JK","INOV.JK",

    # --- ENERGI & BATUBARA ---
    "ADRO.JK","PTBA.JK","ITMG.JK","HRUM.JK","BUMI.JK","DOID.JK","BYAN.JK",
    "GEMS.JK","FIRE.JK","SMMT.JK","GTBO.JK","MYOH.JK","BORN.JK","TOBA.JK",
    "MBAP.JK","DKFT.JK","ARII.JK","PKPK.JK","ABMM.JK","GTSI.JK","HELI.JK",
    "BOSS.JK","BRMS.JK","BSSR.JK","DEWA.JK","ELSA.JK","ENRG.JK","ESSA.JK",
    "INDY.JK","KKGI.JK","MEDC.JK","MITI.JK","PSAB.JK","RUIS.JK","SMRU.JK",
    "TKGA.JK","TPMA.JK","ZINC.JK","CNKO.JK","BIPI.JK","RIGS.JK","SMCB.JK",
    "ATPK.JK","BISI.JK","BNBR.JK","BRAY.JK","COAL.JK","DEWA.JK","DOID.JK",
    "DWGL.JK","ESSA.JK","GTBO.JK","INDY.JK","ITMG.JK","KKGI.JK","MBAP.JK",
    "MYOH.JK","PKPK.JK","PTBA.JK","SMMT.JK","TOBA.JK","ZINC.JK",

    # --- LOGAM & MINERAL ---
    "ANTM.JK","INCO.JK","TINS.JK","MDKA.JK","MBMA.JK","NCKL.JK","NICL.JK",
    "CUAN.JK","IPPE.JK","PSAB.JK","SMRU.JK","TKGA.JK","BRMS.JK","DKFT.JK",
    "ARCI.JK","CKRA.JK","CSIS.JK","DKFT.JK","GEMA.JK","IFSH.JK","INCO.JK",
    "MDKA.JK","NCKL.JK","NICL.JK","PSAB.JK","PURE.JK","SMRU.JK","TINS.JK",

    # --- MINYAK & GAS ---
    "PGAS.JK","AKRA.JK","MEDC.JK","ENRG.JK","ESSA.JK","ELSA.JK","RIGS.JK",
    "BIPI.JK","RUIS.JK","SOCI.JK","WINS.JK","BULL.JK","BLTA.JK","SMDR.JK",
    "ARTI.JK","BEST.JK","EBTKE.JK","HIMU.JK","LAPD.JK","MEDI.JK","MITI.JK",
    "OILS.JK","PGAS.JK","RIGS.JK","SIAP.JK","SURE.JK","TOTL.JK",

    # --- PERKEBUNAN ---
    "AALI.JK","LSIP.JK","SGRO.JK","TBLA.JK","PALM.JK","DSNG.JK","SSMS.JK",
    "BWPT.JK","JAWA.JK","TAPG.JK","ANJT.JK","GOLL.JK","MGRO.JK","SIMP.JK",
    "SMAR.JK","UNSP.JK","PANI.JK","PICO.JK","ALMG.JK","BISI.JK","BNII.JK",
    "BTEK.JK","CSRA.JK","DNSG.JK","GOLL.JK","GPSO.JK","JAWA.JK","KPIG.JK",
    "LSIP.JK","MAGP.JK","MGRO.JK","MSJA.JK","PALM.JK","PANI.JK","SGRO.JK",
    "SIMP.JK","SMAR.JK","SSMS.JK","TAPG.JK","UNSP.JK",

    # --- KONSUMER & MAKANAN MINUMAN ---
    "ICBP.JK","INDF.JK","MYOR.JK","CPIN.JK","ULTJ.JK","DLTA.JK","SKBM.JK",
    "HMSP.JK","GGRM.JK","WIIM.JK","UNVR.JK","KLBF.JK","SIDO.JK","KINO.JK",
    "FAST.JK","FOOD.JK","GULA.JK","AISA.JK","GOOD.JK","HOKI.JK","IIKP.JK",
    "KEJU.JK","MGBR.JK","MOLI.JK","PCAR.JK","PSDN.JK","ROTI.JK","SKLT.JK",
    "STTP.JK","CLEO.JK","CMRY.JK","DMND.JK","ENZO.JK","EPMT.JK","CEKA.JK",
    "ALTO.JK","BTEK.JK","CAMP.JK","CINT.JK","COCO.JK","CSMI.JK","DADA.JK",
    "DFAM.JK","GGRP.JK","GMTD.JK","GUNA.JK","HITS.JK","IBST.JK","ICON.JK",
    "IGAR.JK","IGTA.JK","IMPC.JK","INCI.JK","INRU.JK","IPOL.JK","ISSP.JK",
    "ITIC.JK","JKON.JK","JMAS.JK","JPFA.JK","KBLI.JK","KBLM.JK","KBLV.JK",
    "KDSI.JK","KMTR.JK","KONI.JK","LEAD.JK","LMAX.JK","LMSH.JK","LPLI.JK",
    "LTLS.JK","MAMI.JK","MANG.JK","MBTO.JK","META.JK","MFMI.JK","MGBR.JK",
    "MGLV.JK","MHKI.JK","MKNT.JK","MLBI.JK","MNRJ.JK","MOLI.JK","MRAT.JK",
    "MSIN.JK","NATO.JK","NELY.JK","OCAP.JK","OMRE.JK","OPMS.JK","PADI.JK",
    "PCAR.JK","PHAR.JK","PKPK.JK","PLAS.JK","PMMP.JK","POOL.JK","PSDN.JK",
    "PTIS.JK","PTRO.JK","PUDP.JK","RBOT.JK","RBMS.JK","RDTX.JK","RICY.JK",
    "RMBA.JK","RODA.JK","SAFE.JK","SCBD.JK","SCCO.JK","SDMU.JK","SFAN.JK",
    "SHIP.JK","SINI.JK","SMDM.JK","SMKL.JK","SPMA.JK","SRIL.JK","SRSN.JK",
    "SSTM.JK","TALF.JK","TARA.JK","TCID.JK","TGRA.JK","TIFA.JK","TMPO.JK",
    "TOPS.JK","TRIL.JK","TRIO.JK","TRST.JK","UNIT.JK","UNIC.JK","UNSP.JK",
    "URBN.JK","VRNA.JK","WMUU.JK","WOMF.JK","WTON.JK","YULE.JK",

    # --- RETAIL ---
    "ACES.JK","MAPI.JK","LPPF.JK","RALS.JK","AMRT.JK","MIDI.JK","MPPA.JK",
    "CSAP.JK","SPAR.JK","TGKA.JK","SDPC.JK","HERO.JK","KOIN.JK","RANC.JK",
    "ECII.JK","ERAA.JK","GLOB.JK","MKNT.JK","TRIO.JK","MAPI.JK","MPIX.JK",

    # --- PROPERTI ---
    "BSDE.JK","CTRA.JK","PWON.JK","SMRA.JK","LPKR.JK","ASRI.JK","BEST.JK",
    "DILD.JK","MTLA.JK","APLN.JK","GPRA.JK","SSIA.JK","PJAA.JK","CITY.JK",
    "PURI.JK","ESTA.JK","CBMF.JK","MABA.JK","RISE.JK","PPGL.JK","JGLE.JK",
    "BKSL.JK","COWL.JK","DMAS.JK","EMDE.JK","FORZ.JK","GWSA.JK","IDPR.JK",
    "JPRT.JK","KIJA.JK","LCGP.JK","MDLN.JK","MMLP.JK","NIRO.JK","OMRE.JK",
    "PLIN.JK","PUDP.JK","RBMS.JK","RDTX.JK","RODA.JK","SCBD.JK","SHID.JK",
    "SMCB.JK","TARA.JK","URBN.JK","BAPA.JK","BCAP.JK","BESS.JK","BIMA.JK",
    "CLAY.JK","DAJK.JK","DEWI.JK","DPUM.JK","FAPA.JK","FILM.JK","FISH.JK",
    "FLMC.JK","FORU.JK","GAMA.JK","GBIC.JK","GCEC.JK","GEMA.JK","GMTD.JK",
    "IATA.JK","IFSH.JK","IIKP.JK","INCA.JK","INDX.JK","KARW.JK","KPIG.JK",
    "LPCK.JK","MDKI.JK","MDRN.JK","MHKI.JK","MIRA.JK","MTPS.JK","NZIA.JK",
    "PADI.JK","PANI.JK","PBSA.JK","PICO.JK","PKPK.JK","PLAS.JK","PLIN.JK",
    "SMKL.JK","SONA.JK","TGRA.JK","TRIL.JK","WMUU.JK",

    # --- INFRASTRUKTUR & KONSTRUKSI ---
    "JSMR.JK","WIKA.JK","PTPP.JK","WSKT.JK","ADHI.JK","TOTL.JK","ACST.JK",
    "NRCA.JK","PBSA.JK","PPRE.JK","WTON.JK","DGIK.JK","IDPR.JK","MMLP.JK",
    "AISA.JK","AMFG.JK","ARNA.JK","BUDI.JK","CLEO.JK","CMRY.JK","DMND.JK",
    "ENZO.JK","EPMT.JK","GOOD.JK","HOKI.JK","IIKP.JK","INCA.JK","INRU.JK",
    "IPOL.JK","ISSP.JK","ITIC.JK","JKON.JK","JMAS.JK","KBLI.JK","KBLM.JK",
    "KDSI.JK","KMTR.JK","KONI.JK","LEAD.JK","LMAX.JK","LMSH.JK","LPLI.JK",

    # --- TRANSPORTASI ---
    "BIRD.JK","MPMX.JK","TAXI.JK","WEHA.JK","TMAS.JK","IPCC.JK","NELY.JK",
    "MBSS.JK","SMDR.JK","BLTA.JK","BULL.JK","WINS.JK","SOCI.JK","LRNA.JK",
    "ASSA.JK","BBRM.JK","CMPP.JK","GIAA.JK","IATA.JK","INDX.JK","KARW.JK",
    "MIRA.JK","SAFE.JK","SHIP.JK","TR34.JK","ZBRA.JK","TPMA.JK","NELY.JK",
    "APOL.JK","ASSA.JK","BBRM.JK","CMPP.JK","GIAA.JK","IPCM.JK","KARW.JK",
    "LRNA.JK","MBSS.JK","MIRA.JK","NELY.JK","PTIS.JK","SAFE.JK","SHIP.JK",
    "SMDR.JK","TAXI.JK","TMAS.JK","TR34.JK","WEHA.JK","WINS.JK","ZBRA.JK",

    # --- KESEHATAN & FARMASI ---
    "KAEF.JK","PYFA.JK","TSPC.JK","MERK.JK","INAF.JK","PRDA.JK","SAME.JK",
    "BMHS.JK","PRIM.JK","HEAL.JK","MIKA.JK","SILO.JK","MLBI.JK","PEHA.JK",
    "AHAP.JK","DGNS.JK","DVLA.JK","EKAD.JK","ERBA.JK","GIFT.JK","IRRA.JK",
    "MDRN.JK","MTPS.JK","PHAR.JK","SOHO.JK","SRAJ.JK","OMED.JK","CARE.JK",
    "LABS.JK","MEDS.JK","PEVE.JK","RSGK.JK","RSIA.JK","SGER.JK",

    # --- OTOMOTIF & MANUFAKTUR ---
    "ASII.JK","AUTO.JK","SMSM.JK","IMAS.JK","INDS.JK","LPIN.JK","MASA.JK",
    "NIPS.JK","PRAS.JK","SRIL.JK","ADMG.JK","BOLT.JK","BRAM.JK","GDYR.JK",
    "GJTL.JK","MYTX.JK","RICY.JK","SSTM.JK","UNIT.JK","ADMG.JK","AIMS.JK",
    "ALKA.JK","ALMI.JK","BAJA.JK","BELL.JK","BIMA.JK","BTON.JK","CTBN.JK",
    "GDST.JK","GGRP.JK","GJTL.JK","GMTD.JK","IGAR.JK","IGTA.JK","IMPC.JK",
    "INAI.JK","INCI.JK","INDS.JK","ISSP.JK","ITIC.JK","JKON.JK","JPFA.JK",
    "KBLI.JK","KBLM.JK","KDSI.JK","KMTR.JK","KONI.JK","LMAX.JK","LMSH.JK",
    "MAIN.JK","MARK.JK","MASA.JK","MDKI.JK","MLIA.JK","MYTX.JK","NIPS.JK",
    "PICO.JK","PLAS.JK","PRAS.JK","RICY.JK","SCCO.JK","SFAN.JK","SMSM.JK",
    "SPMA.JK","SRIL.JK","SRSN.JK","SSTM.JK","TALF.JK","TOTO.JK","TRST.JK",
    "UNIC.JK","UNIT.JK","WTON.JK",

    # --- SEMEN & MATERIAL BANGUNAN ---
    "SMGR.JK","INTP.JK","SMBR.JK","WTON.JK","AMFG.JK","ARNA.JK","KIAS.JK",
    "MLIA.JK","TOTO.JK","MARK.JK","MDKI.JK","TPIA.JK","UNIC.JK","BTON.JK",
    "ALKA.JK","ALMI.JK","BAJA.JK","CTBN.JK","GDST.JK","INAI.JK","ISSP.JK",
    "JKON.JK","KBLI.JK","KBLM.JK","LMSH.JK","SCCO.JK","SPMA.JK","WTON.JK",

    # --- KEUANGAN NON-BANK ---
    "ADMF.JK","BFIN.JK","HDFA.JK","MFIN.JK","TIFA.JK","WOMF.JK","VRNA.JK",
    "CFIN.JK","DEFI.JK","FINN.JK","IBFN.JK","IMJS.JK","PNIN.JK","SMMA.JK",
    "TRUS.JK","VICO.JK","YULE.JK","AMOR.JK","APIC.JK","ASRM.JK","ASJT.JK",
    "BPII.JK","CASA.JK","GSMF.JK","KREN.JK","LPGI.JK","MREI.JK","MTWI.JK",
    "PNIN.JK","PNLF.JK","POOL.JK","SMMA.JK","SUGI.JK","TRIM.JK","TRUS.JK",
    "VICO.JK","VRNA.JK","WSBP.JK","YULE.JK",

    # --- MEDIA & HIBURAN ---
    "MNCN.JK","SCMA.JK","EMTK.JK","VIVA.JK","FILM.JK","JTPE.JK","KBLV.JK",
    "MDIA.JK","MSKY.JK","TMPO.JK","ABBA.JK","DMMX.JK","FORU.JK","JTPE.JK",

    # --- AGRIKULTUR LAINNYA ---
    "BISI.JK","CSRA.JK","DNSG.JK","GOLL.JK","GPSO.JK","LSIP.JK","MAGP.JK",
    "MSJA.JK","PALM.JK","PANI.JK","SGRO.JK","SIMP.JK","SMAR.JK","SSMS.JK",
    "TAPG.JK","UNSP.JK","BWPT.JK","DSNG.JK","JAWA.JK","TBLA.JK",

    # --- SAHAM GORENGAN & SPEKULATIF ---
    "GOTO.JK","BUKA.JK","ARTO.JK","DCII.JK","DEWA.JK","MBMA.JK","NCKL.JK",
    "BRMS.JK","CUAN.JK","WIFI.JK","INET.JK","STRK.JK","NFCX.JK","FIRE.JK",
    "NICE.JK","SULI.JK","CBMF.JK","KRYA.JK","MABA.JK","RISE.JK","PPGL.JK",
    "HAJJ.JK","HOPE.JK","FOOD.JK","GULA.JK","MRAT.JK","KICI.JK","BEKS.JK",
    "MSIN.JK","AKKU.JK","BHAT.JK","BBKP.JK","BABP.JK","AGRS.JK","BBYB.JK",
    "CITY.JK","PURI.JK","RANC.JK","ESTA.JK","FORZ.JK","IPPE.JK","LCGP.JK",
    "MPRO.JK","NZIA.JK","SMKL.JK","SONA.JK","TGRA.JK","TRIL.JK","WMUU.JK",
    "AMAN.JK","ANDI.JK","BAPA.JK","BCAP.JK","BESS.JK","BIMA.JK","BUDI.JK",
    "CAMP.JK","CEKA.JK","CINT.JK","CLAY.JK","COCO.JK","CSMI.JK","DADA.JK",
    "DAJK.JK","DEWI.JK","DFAM.JK","DOOH.JK","DPUM.JK","ECII.JK","ENVY.JK",
    "EURO.JK","FAPA.JK","FISH.JK","FLMC.JK","GAMA.JK","GBIC.JK","GCEC.JK",
    "IIKP.JK","INCA.JK","INRU.JK","IPOL.JK","JMAS.JK","KPIG.JK","LEAD.JK",
    "LPLI.JK","LTLS.JK","MAMI.JK","MANG.JK","MBTO.JK","META.JK","MFMI.JK",
    "MGLV.JK","MKNT.JK","MNRJ.JK","NATO.JK","NIRO.JK","NRCA.JK","OCAP.JK",
    "OILS.JK","OPMS.JK","PBSA.JK","PPRE.JK","PTRO.JK","PURE.JK","RBOT.JK",
    "SAFE.JK","SDMU.JK","SINI.JK","SMDM.JK","WSBP.JK","ZBRA.JK","OMED.JK",
    "CARE.JK","LABS.JK","MEDS.JK","PEVE.JK","RSGK.JK","RSIA.JK","SGER.JK",
    "SRAJ.JK","ABBA.JK","MDIA.JK","MSKY.JK","VIVA.JK","AIMS.JK","ALKA.JK",
    "ALMI.JK","BAJA.JK","BELL.JK","BTON.JK","CTBN.JK","GDST.JK","INAI.JK",
    "MAIN.JK","AMOR.JK","APIC.JK","ASRM.JK","CASA.JK","GSMF.JK","KREN.JK",
    "LPGI.JK","MREI.JK","MTWI.JK","PNLF.JK","SUGI.JK","WSBP.JK","IPCM.JK",
    "APOL.JK","ZBRA.JK","LPCK.JK","BANO.JK","BPTR.JK","CSRA.JK","DNSG.JK",
    "GPSO.JK","MAGP.JK","MSJA.JK","PEVE.JK","RSGK.JK","RSIA.JK","SGER.JK",
]


def get_idx_tickers() -> List[str]:
    tickers = sorted(list(dict.fromkeys(ALL_IDX_TICKERS)))
    logger.info(f"Total tickers to scan: {len(tickers)}")
    return tickers


def get_ticker_base(ticker: str) -> str:
    return ticker.replace(".JK", "")
