"""
screener/tickers.py — Full IDX Coverage

Semua ~950 ticker IDX yang aktif terdaftar.
Dikelompokkan per sektor untuk maintenance yang mudah.
"""

import logging
from typing import List

logger = logging.getLogger(__name__)

ALL_IDX_TICKERS: List[str] = [
    # --- PERBANKAN ---
    "BBCA.JK","BBRI.JK","BMRI.JK","BBNI.JK","BRIS.JK","BNGA.JK","BJBR.JK",
    "BDMN.JK","NISP.JK","PNBN.JK","MEGA.JK","BJTM.JK","BTPS.JK","NOBU.JK",
    "AGRO.JK","BBYB.JK","BBKP.JK","BABP.JK","AGRS.JK","BMAS.JK","BCIC.JK",
    "BGTG.JK","BINA.JK","BKSW.JK","BMBL.JK","BNBA.JK","BNII.JK","BPII.JK",
    "BSIM.JK","BTPN.JK","DNAR.JK","INPC.JK","MAYA.JK","MCOR.JK","NAGA.JK",
    "PNBS.JK","SDRA.JK","TRIM.JK","ASDM.JK","ASJT.JK","BANK.JK","BHAT.JK",

    # --- TELEKOMUNIKASI & TEKNOLOGI ---
    "TLKM.JK","EXCL.JK","ISAT.JK","FREN.JK","MNCN.JK","SCMA.JK","EMTK.JK",
    "TOWR.JK","TBIG.JK","LINK.JK","MTEL.JK","DCII.JK","WIFI.JK","INET.JK",
    "MLPT.JK","DMMX.JK","DNET.JK","MTDL.JK","LUCK.JK","SWAT.JK","HAIS.JK",
    "TFAS.JK","EDGE.JK","NFCX.JK","STRK.JK","TECH.JK","ATIC.JK","CENT.JK",
    "IPTV.JK","JGLE.JK","KIOS.JK","MCAS.JK","MPIX.JK","SKYB.JK","TELE.JK",

    # --- ENERGI & PERTAMBANGAN BATUBARA ---
    "ADRO.JK","PTBA.JK","ITMG.JK","HRUM.JK","BUMI.JK","DOID.JK","BYAN.JK",
    "GEMS.JK","FIRE.JK","SMMT.JK","GTBO.JK","MYOH.JK","BORN.JK","TOBA.JK",
    "MBAP.JK","DKFT.JK","ARII.JK","PKPK.JK","ABMM.JK","GTSI.JK","HELI.JK",
    "BOSS.JK","BRMS.JK","BSSR.JK","DEWA.JK","ELSA.JK","ENRG.JK","ESSA.JK",
    "INDY.JK","KKGI.JK","MEDC.JK","MITI.JK","PSAB.JK","RUIS.JK","SMRU.JK",
    "TKGA.JK","TPMA.JK","ZINC.JK","CNKO.JK","BIPI.JK","RIGS.JK",

    # --- LOGAM & MINERAL ---
    "ANTM.JK","INCO.JK","TINS.JK","MDKA.JK","MBMA.JK","NCKL.JK","NICL.JK",
    "CUAN.JK","BRMS.JK","DKFT.JK","ITMG.JK","NCKL.JK","PSAB.JK","SMRU.JK",
    "ZINC.JK","IPPE.JK","MITI.JK","TKGA.JK",

    # --- MINYAK & GAS ---
    "PGAS.JK","AKRA.JK","MEDC.JK","ENRG.JK","ESSA.JK","ELSA.JK","RIGS.JK",
    "BIPI.JK","RUIS.JK","SOCI.JK","WINS.JK","BULL.JK","BLTA.JK","SMDR.JK",

    # --- PERKEBUNAN ---
    "AALI.JK","LSIP.JK","SGRO.JK","TBLA.JK","PALM.JK","DSNG.JK","SSMS.JK",
    "BWPT.JK","JAWA.JK","TAPG.JK","ANJT.JK","BNII.JK","GOLL.JK","MGRO.JK",
    "PANI.JK","PICO.JK","SIMP.JK","SMAR.JK","UNSP.JK",

    # --- KONSUMER & MAKANAN MINUMAN ---
    "ICBP.JK","INDF.JK","MYOR.JK","CPIN.JK","ULTJ.JK","DLTA.JK","SKBM.JK",
    "HMSP.JK","GGRM.JK","WIIM.JK","UNVR.JK","KLBF.JK","SIDO.JK","KINO.JK",
    "FAST.JK","FOOD.JK","GULA.JK","AISA.JK","GOOD.JK","HOKI.JK","IIKP.JK",
    "INDF.JK","KEJU.JK","MGBR.JK","MOLI.JK","PCAR.JK","PSDN.JK","ROTI.JK",
    "SKLT.JK","STTP.JK","TBLA.JK","TRST.JK","TSPC.JK","ULTJ.JK","UNVR.JK",
    "CLEO.JK","CMRY.JK","DMND.JK","ENZO.JK","EPMT.JK","GGRM.JK","HOKI.JK",

    # --- RETAIL ---
    "ACES.JK","MAPI.JK","LPPF.JK","RALS.JK","AMRT.JK","MIDI.JK","MPPA.JK",
    "CSAP.JK","SPAR.JK","TGKA.JK","SDPC.JK","HERO.JK","KOIN.JK","RANC.JK",
    "CENT.JK","ECII.JK","ERAA.JK","GLOB.JK","KIOS.JK","MAPI.JK","MKNT.JK",
    "MPIX.JK","TELE.JK","TRIO.JK",

    # --- PROPERTI ---
    "BSDE.JK","CTRA.JK","PWON.JK","SMRA.JK","LPKR.JK","ASRI.JK","BEST.JK",
    "DILD.JK","MTLA.JK","APLN.JK","GPRA.JK","SSIA.JK","PJAA.JK","CITY.JK",
    "PURI.JK","ESTA.JK","CBMF.JK","MABA.JK","RISE.JK","PPGL.JK","JGLE.JK",
    "BKSL.JK","COWL.JK","DMAS.JK","EMDE.JK","FORZ.JK","GWSA.JK","IDPR.JK",
    "JPRT.JK","KIJA.JK","LCGP.JK","MDLN.JK","MMLP.JK","NIRO.JK","OMRE.JK",
    "PLIN.JK","PUDP.JK","RBMS.JK","RDTX.JK","RODA.JK","SCBD.JK","SHID.JK",
    "SMCB.JK","TARA.JK","URBN.JK","WIKA.JK","WSKT.JK","PTPP.JK","ADHI.JK",

    # --- INFRASTRUKTUR & KONSTRUKSI ---
    "JSMR.JK","WIKA.JK","PTPP.JK","WSKT.JK","ADHI.JK","TOTL.JK","ACST.JK",
    "NRCA.JK","PBSA.JK","PPRE.JK","WTON.JK","DGIK.JK","IDPR.JK","MMLP.JK",

    # --- TRANSPORTASI ---
    "BIRD.JK","MPMX.JK","TAXI.JK","WEHA.JK","TMAS.JK","IPCC.JK","NELY.JK",
    "MBSS.JK","SMDR.JK","BLTA.JK","BULL.JK","WINS.JK","SOCI.JK","LRNA.JK",
    "ASSA.JK","BBRM.JK","CMPP.JK","GIAA.JK","IATA.JK","INDX.JK","KARW.JK",
    "MIRA.JK","SAFE.JK","SHIP.JK","TPMA.JK","TR34.JK",

    # --- KESEHATAN & FARMASI ---
    "KAEF.JK","PYFA.JK","TSPC.JK","MERK.JK","INAF.JK","PRDA.JK","SAME.JK",
    "BMHS.JK","PRIM.JK","HEAL.JK","MIKA.JK","SILO.JK","MLBI.JK","PEHA.JK",
    "AHAP.JK","DGNS.JK","DVLA.JK","EKAD.JK","ERBA.JK","GIFT.JK","IRRA.JK",
    "KLBF.JK","MDRN.JK","MIKA.JK","MTPS.JK","PHAR.JK","SIDO.JK","SOHO.JK",

    # --- OTOMOTIF & MANUFAKTUR ---
    "ASII.JK","AUTO.JK","SMSM.JK","IMAS.JK","INDS.JK","LPIN.JK","MASA.JK",
    "NIPS.JK","PRAS.JK","SRIL.JK","ADMG.JK","BOLT.JK","BRAM.JK","GDYR.JK",
    "GJTL.JK","IMAS.JK","INDS.JK","LPIN.JK","MASA.JK","MYTX.JK","NIPS.JK",
    "PRAS.JK","RICY.JK","SMSM.JK","SSTM.JK","UNIT.JK",

    # --- SEMEN & MATERIAL ---
    "SMGR.JK","INTP.JK","SMBR.JK","WTON.JK","AMFG.JK","ARNA.JK","KIAS.JK",
    "MLIA.JK","TOTO.JK","MARK.JK","MDKI.JK","TPIA.JK","UNIC.JK",

    # --- KEUANGAN NON-BANK ---
    "ADMF.JK","BFIN.JK","HDFA.JK","MFIN.JK","TIFA.JK","WOMF.JK","VRNA.JK",
    "CFIN.JK","DEFI.JK","FINN.JK","IBFN.JK","IMJS.JK","MPMX.JK","PNIN.JK",
    "SMMA.JK","TRUS.JK","VICO.JK","YULE.JK",

    # --- SAHAM GORENGAN & SPEKULATIF POPULER ---
    "GOTO.JK","BUKA.JK","ARTO.JK","DCII.JK","DEWA.JK","MBMA.JK","NCKL.JK",
    "BRMS.JK","CUAN.JK","WIFI.JK","INET.JK","STRK.JK","NFCX.JK","FIRE.JK",
    "NICE.JK","SULI.JK","CBMF.JK","KRYA.JK","MABA.JK","RISE.JK","PPGL.JK",
    "HAJJ.JK","HOPE.JK","FOOD.JK","GULA.JK","YULE.JK","MRAT.JK","KICI.JK",
    "BEKS.JK","MSIN.JK","AKKU.JK","SKYB.JK","BHAT.JK","BBKP.JK","BABP.JK",
    "AGRS.JK","BBYB.JK","NOBU.JK","DNAR.JK","CITY.JK","PURI.JK","RANC.JK",
    "ESTA.JK","FORZ.JK","IPPE.JK","JGLE.JK","KIOS.JK","LCGP.JK","MPRO.JK",
    "NZIA.JK","SMKL.JK","SONA.JK","TGRA.JK","TRIL.JK","WMUU.JK","AMAN.JK",
    "ANDI.JK","BAPA.JK","BCAP.JK","BESS.JK","BIMA.JK","BPII.JK","BUDI.JK",
    "CAMP.JK","CEKA.JK","CINT.JK","CLAY.JK","COCO.JK","CSMI.JK","DADA.JK",
    "DAJK.JK","DEWI.JK","DFAM.JK","DIVA.JK","DOOH.JK","DPUM.JK","DWGL.JK",
    "ECII.JK","ENVY.JK","EURO.JK","FAPA.JK","FILM.JK","FISH.JK","FLMC.JK",
    "FORU.JK","GAMA.JK","GBIC.JK","GCEC.JK","GEMA.JK","GGRP.JK","GMTD.JK",
    "GUNA.JK","HELI.JK","HITS.JK","IATA.JK","IBST.JK","ICON.JK","IFSH.JK",
    "IGAR.JK","IGTA.JK","IIKP.JK","IMPC.JK","INCI.JK","INPC.JK","INRU.JK",
    "IPOL.JK","ISSP.JK","ITIC.JK","JKON.JK","JMAS.JK","JPFA.JK","KBLI.JK",
    "KBLM.JK","KBLV.JK","KDSI.JK","KEJU.JK","KMTR.JK","KONI.JK","KPIG.JK",
    "LEAD.JK","LMAX.JK","LMSH.JK","LPLI.JK","LTLS.JK","MABA.JK","MAMI.JK",
    "MANG.JK","MAPI.JK","MBTO.JK","MDKI.JK","MERK.JK","META.JK","MFMI.JK",
    "MGBR.JK","MGLV.JK","MHKI.JK","MITI.JK","MKNT.JK","MLBI.JK","MLIA.JK",
    "MNCN.JK","MNRJ.JK","MOLI.JK","MPMX.JK","MRAT.JK","MSIN.JK","MTDL.JK",
    "MTLA.JK","MYOH.JK","NAGA.JK","NATO.JK","NELY.JK","NIRO.JK","NRCA.JK",
    "OCAP.JK","OILS.JK","OMRE.JK","OPMS.JK","PADI.JK","PANI.JK","PCAR.JK",
    "PEHA.JK","PGAS.JK","PHAR.JK","PICO.JK","PJAA.JK","PKPK.JK","PLAS.JK",
    "PLIN.JK","PMMP.JK","PNIN.JK","POOL.JK","PPGL.JK","PPRE.JK","PRIM.JK",
    "PSAB.JK","PSDN.JK","PTBA.JK","PTIS.JK","PTPP.JK","PTRO.JK","PUDP.JK",
    "PURE.JK","RBOT.JK","RBMS.JK","RDTX.JK","RICY.JK","RIGS.JK","RISE.JK",
    "RMBA.JK","RODA.JK","ROTI.JK","SAFE.JK","SAME.JK","SCBD.JK","SCCO.JK",
    "SDMU.JK","SDRA.JK","SFAN.JK","SGRO.JK","SHIP.JK","SHID.JK","SILO.JK",
    "SIMP.JK","SINI.JK","SKLT.JK","SMCB.JK","SMDM.JK","SMGR.JK","SMKL.JK",
    "SMMT.JK","SMRA.JK","SMRU.JK","SOCI.JK","SOHO.JK","SONA.JK","SPMA.JK",
    "SRIL.JK","SRSN.JK","SSTM.JK","STTP.JK","SULI.JK","SWAT.JK","TALF.JK",
    "TARA.JK","TAXI.JK","TBIG.JK","TBLA.JK","TCID.JK","TFAS.JK","TGKA.JK",
    "TGRA.JK","TIFA.JK","TINS.JK","TKGA.JK","TMAS.JK","TMPO.JK","TOBA.JK",
    "TOPS.JK","TOTO.JK","TOTL.JK","TPMA.JK","TRIL.JK","TRIO.JK","TRST.JK",
    "TSPC.JK","UNIT.JK","UNIC.JK","UNSP.JK","URBN.JK","VICO.JK","VRNA.JK",
    "WEHA.JK","WMUU.JK","WOMF.JK","WSKT.JK","WTON.JK","YULE.JK","ZINC.JK",
    # --- TAMBAHAN FULL COVERAGE IDX ---
    "AAJI.JK","AALI.JK","ABBA.JK","ABDA.JK","ABMM.JK","ACES.JK","ACES.JK",
    "ACST.JK","ADES.JK","ADHI.JK","ADMF.JK","ADMG.JK","ADMR.JK","AGAR.JK",
    "AGII.JK","AGRO.JK","AGRS.JK","AHAP.JK","AIMS.JK","AISA.JK","AKKU.JK",
"AKPI.JK","AKRA.JK","AKSI.JK","ALDO.JK","ALKA.JK","AMAG.JK","AMAN.JK",
"AMAR.JK","AMFG.JK","AMIN.JK","AMMN.JK","AMMS.JK","AMOR.JK","AMRT.JK",
"ANDI.JK","ANJT.JK","ANTM.JK","APEX.JK","APIC.JK","APII.JK","APLI.JK",
"APLN.JK","ARCI.JK","ARGO.JK","ARKA.JK","ARKO.JK","ARNA.JK","ARTA.JK",
"ARTO.JK","ASBI.JK","ASDM.JK","ASGR.JK","ASII.JK","ASJT.JK","ASLC.JK",
"ASMI.JK","ASPI.JK","ASRI.JK","ASSA.JK","ATAP.JK","ATIC.JK","AUTO.JK",
"AWAN.JK","BABP.JK","BACA.JK","BAJA.JK","BALI.JK","BANK.JK","BAPA.JK",
"BAPI.JK","BATA.JK","BAYU.JK","BBCA.JK","BBHI.JK","BBKP.JK","BBMD.JK",
"BBNI.JK","BBRI.JK","BBRM.JK","BBSS.JK","BBTN.JK","BBYB.JK","BCAP.JK",
"BCIC.JK","BDKR.JK","BDMN.JK","BEBS.JK","BEKS.JK","BEST.JK","BFIN.JK",
"BGTG.JK","BHAT.JK","BINA.JK","BIPI.JK","BIRD.JK","BISI.JK","BJBR.JK",
"BJTM.JK","BKDP.JK","BKSL.JK","BLTA.JK","BLUE.JK","BMAS.JK","BMHS.JK",
"BMRI.JK","BMSR.JK","BMTR.JK","BNBA.JK","BNBR.JK","BNGA.JK","BNII.JK",
"BNLI.JK","BOLT.JK","BOSS.JK","BPFI.JK","BPII.JK","BPTR.JK","BRAM.JK",
"BRIS.JK","BRMS.JK","BRNA.JK","BROT.JK","BSDE.JK","BSIM.JK","BSML.JK",
"BSSR.JK","BTEL.JK","BTON.JK","BTPN.JK","BTPS.JK","BUAH.JK","BUDI.JK",
"BUKA.JK","BUMI.JK","BULL.JK","BUVA.JK","BVIC.JK","BWPT.JK","BYAN.JK",
"CAKK.JK","CAMP.JK","CANI.JK","CARE.JK","CARS.JK","CASA.JK","CBMF.JK",
"CBPE.JK","CBRE.JK","CCSI.JK","CEKA.JK","CENT.JK","CFIN.JK","CGAS.JK",
"CHEK.JK","CINT.JK","CITY.JK","CLAY.JK","CLEO.JK","CMNP.JK","CMRY.JK",
"CNKO.JK","COCO.JK","CPIN.JK","CSAP.JK","CSIS.JK","CTBN.JK","CTRA.JK",
"CUAN.JK","DATA.JK","DAYA.JK","DCII.JK","DEFI.JK","DEPO.JK","DGIK.JK",
"DGNS.JK","DILD.JK","DKFT.JK","DLTA.JK","DMAS.JK","DMND.JK","DOID.JK",
"DOOH.JK","DSFI.JK","DSNG.JK","DSSA.JK","DVLA.JK","DWGL.JK","EDGE.JK",
"EKAD.JK","ELSA.JK","ELTY.JK","EMDE.JK","EMTK.JK","ENRG.JK","ENVY.JK",
"EPMT.JK","ERAA.JK","ERAL.JK","ESSA.JK","ESTA.JK","EURO.JK","EXCL.JK",
"FAST.JK","FIRE.JK","FISH.JK","FITT.JK","FORU.JK","FREN.JK","GAMA.JK",
"GEMS.JK","GGRM.JK","GIAA.JK","GJTL.JK","GLOB.JK","GMFI.JK","GOOD.JK",
"GOTO.JK","GPRA.JK","GSMF.JK","GTBO.JK","GTRA.JK","GTSI.JK","GULA.JK",
"HADE.JK","HAIS.JK","HEAL.JK","HELI.JK","HERO.JK","HILL.JK","HITS.JK",
"HMSP.JK","HOKI.JK","HOPE.JK","HRUM.JK","HUMI.JK","IATA.JK","IBFN.JK",
"ICBP.JK","ICON.JK","IDEA.JK","IFII.JK","IGAR.JK","IIKP.JK","IKAI.JK",
"IMAS.JK","IMJS.JK","IMPC.JK","INAF.JK","INCF.JK","INCO.JK","INDF.JK",
"INDR.JK","INDX.JK","INDY.JK","INET.JK","INPC.JK","INTP.JK","IPCC.JK",
"IPCM.JK","IPOL.JK","IPPE.JK","ISAT.JK","ISSP.JK","ITIC.JK","ITMA.JK",
"ITMG.JK","JARR.JK","JAST.JK","JATI.JK","JAWA.JK","JGLE.JK","JKON.JK",
"JPFA.JK","JSMR.JK","JTPE.JK","KAEF.JK","KARW.JK","KBAG.JK","KBLI.JK",
"KBLM.JK","KBLV.JK","KDSI.JK","KEEN.JK","KEJU.JK","KIAS.JK","KINO.JK",
"KIOS.JK","KKES.JK","KLBF.JK","KMDS.JK","KMTR.JK","KOBX.JK","KOCI.JK",
"KOIN.JK","KONI.JK","KPAL.JK","KPIG.JK","KRAH.JK","KREN.JK","KRYA.JK",
"LABA.JK","LAND.JK","LAPD.JK","LCGP.JK","LEAD.JK","LIFE.JK","LINK.JK",
"LION.JK","LMAS.JK","LMPI.JK","LPCK.JK","LPIN.JK","LPKR.JK","LPLI.JK",
"LPPF.JK","LRNA.JK","LSIP.JK","LUCK.JK","MAIN.JK","MAMI.JK","MAPI.JK",
"MARK.JK","MASA.JK","MBAP.JK","MBMA.JK","MBSS.JK","MCAS.JK","MCOR.JK",
"MDKA.JK","MDKI.JK","MDLN.JK","MEDC.JK","MEGA.JK","MERK.JK","META.JK",
"MFIN.JK","MFMI.JK","MGRO.JK","MHKI.JK","MIDI.JK","MIKA.JK","MINE.JK",
"MITI.JK","MKNT.JK","MKPI.JK","MLBI.JK","MLIA.JK","MLPL.JK","MLPT.JK",
"MNCN.JK","MPMX.JK","MPPA.JK","MPIX.JK","MPRO.JK","MREI.JK","MSIN.JK",
"MTDL.JK","MTEL.JK","MTLA.JK","MTPS.JK","MYOH.JK","MYOR.JK","MYRX.JK",
"NATO.JK","NCKL.JK","NELY.JK","NETV.JK","NICL.JK","NIKL.JK","NINE.JK",
"NIRO.JK","NISP.JK","NOBU.JK","NRCA.JK","NZIA.JK","OASA.JK","OBAT.JK",
"OILS.JK","OMED.JK","OMRE.JK","OPMS.JK","PACK.JK","PALM.JK","PANI.JK",
"PBID.JK","PBSA.JK","PCAR.JK","PGAS.JK","PGEO.JK","PGJO.JK","PHAR.JK",
"PICO.JK","PJAA.JK","PKPK.JK","PLAN.JK","PLAS.JK","PLIN.JK","PMMP.JK",
"PNBN.JK","PNBS.JK","PNGO.JK","PNIN.JK","PNLF.JK","POLA.JK","POLI.JK",
"POOL.JK","PORT.JK","POWR.JK","PPGL.JK","PPRE.JK","PTBA.JK","PTIS.JK",
"PTPP.JK","PTRO.JK","PUDP.JK","PURE.JK","PURI.JK","PWON.JK","PYFA.JK",
"RAAM.JK","RALS.JK","RANC.JK","RBMS.JK","RDTX.JK","RGAS.JK","RICY.JK",
"RIGS.JK","RISE.JK","RMBA.JK","RMKE.JK","RODA.JK","ROTI.JK","RUIS.JK",
"SAFE.JK","SAME.JK","SAPX.JK","SCBD.JK","SCMA.JK","SDMU.JK","SDPC.JK",
"SDRA.JK","SFAN.JK","SGER.JK","SGRO.JK","SHIP.JK","SHID.JK","SIDO.JK",
"SILO.JK","SIMP.JK","SINI.JK","SKBM.JK","SKLT.JK","SKYB.JK","SMAR.JK",
"SMBR.JK","SMCB.JK","SMDM.JK","SMDR.JK","SMGR.JK","SMKL.JK","SMMT.JK",
"SMRA.JK","SMRU.JK","SMSM.JK","SOCI.JK","SOHO.JK","SONA.JK","SPAR.JK",
"SPMA.JK","SRIL.JK","SRSN.JK","SSIA.JK","SSMS.JK","STAR.JK","STTP.JK",
"STRK.JK","SULI.JK","SUNI.JK","SWAT.JK","TALF.JK","TAPG.JK","TARA.JK",
"TAXI.JK","TBIG.JK","TBLA.JK","TCID.JK","TECH.JK","TELE.JK","TFAS.JK",
"TGKA.JK","TGRA.JK","TIFA.JK","TINS.JK","TKGA.JK","TLKM.JK","TMAS.JK",
"TMPO.JK","TOBA.JK","TOOL.JK","TOPS.JK","TOTO.JK","TOTL.JK","TOWR.JK",
"TPMA.JK","TRGU.JK","TRIL.JK","TRIM.JK","TRIO.JK","TRST.JK","TSPC.JK",
"ULTJ.JK","UNIC.JK","UNSP.JK","UNTR.JK","UNVR.JK","URBN.JK","VKTR.JK",
"VRNA.JK","WEGE.JK","WEHA.JK","WIFI.JK","WIIM.JK","WIKA.JK","WINS.JK",
"WIRG.JK","WMUU.JK","WOMF.JK","WSBP.JK","WSKT.JK","WTON.JK","ZINC.JK",

]


def get_idx_tickers() -> List[str]:
    # Deduplicate dan sort
    tickers = sorted(list(dict.fromkeys(ALL_IDX_TICKERS)))
    logger.info(f"Total tickers to scan: {len(tickers)}")
    return tickers


def get_ticker_base(ticker: str) -> str:
    return ticker.replace(".JK", "")
